let variedadProductos = [

	{id: 1, nombre: "Baguette", tipo: "Panes", unidad: "Precio x kg", precio: 70, img: "Imagenes/Panes/Baguette.jpg"},
	{id: 2, nombre: "Cremona", tipo: "Panes", unidad: "Precio x kg", precio: 230, img: "Imagenes/Panes/Cremona.jpg"},
	{id: 3, nombre: "Flauta", tipo: "Panes", unidad: "Precio x kg", precio: 130, img: "Imagenes/Panes/Flauta.jpg"},
	{id: 4, nombre: "Fugacita", tipo: "Panes", unidad: "Precio x kg", precio: 240, img: "Imagenes/Panes/Fugacita.jpg"},
	{id: 5, nombre: "Pan de Campo", tipo: "Panes", unidad: "Precio x unidad", precio: 160, img: "Imagenes/Panes/Pan de Campo.jpg"},
	{id: 6, nombre: "Arabe", tipo: "Panes", unidad: "Precio x docena", precio: 260, img: "Imagenes/Panes/Arabe.jpg"},
	{id: 7, nombre: "Budin", tipo: "Dulces", unidad: "Precio x unidad", precio: 360, img: "Imagenes/Dulces/Budin.jpg"},
	{id: 8, nombre: "Cookies", tipo: "Dulces", unidad: "Precio x kg", precio: 900, img: "Imagenes/Dulces/Cookies.jpg"},
	{id: 9, nombre: "Medialunas", tipo: "Dulces", unidad: "Precio x docena", precio: 360, img: "Imagenes/Dulces/Medialunas.jpg"},
	{id: 10, nombre: "Merengues", tipo: "Dulces", unidad: "Precio x kg", precio: 1700, img: "Imagenes/Dulces/Merengues.jpg"},
	{id: 11, nombre: "Muffins", tipo: "Dulces", unidad: "Precio x unidad", precio: 140, img: "Imagenes/Dulces/Muffins.jpg"},
	{id: 12, nombre: "Pepas", tipo: "Dulces", unidad: "Precio x kg", precio: 900, img: "Imagenes/Dulces/Pepas.jpg"},
	{id: 13, nombre: "Bizcochitos", tipo: "Salados", unidad: "Precio x kg", precio: 700, img: "Imagenes/Salados/Bizcochitos.jpg"},
	{id: 14, nombre: "Chipa", tipo: "Salados", unidad: "Precio x kg", precio: 900, img: "Imagenes/Salados/Chipa.jpg"},
	{id: 15, nombre: "Marineras", tipo: "Salados", unidad: "Precio x 180g", precio: 120, img: "Imagenes/Salados/Marineras.jpg"},
	{id: 16, nombre: "Marineritas", tipo: "Salados", unidad: "Precio x 180g", precio: 120, img: "Imagenes/Salados/Marineritas.jpg"},
	{id: 17, nombre: "Pizzas", tipo: "Salados", unidad: "Precio x unidad", precio: 70, img: "Imagenes/Salados/Pizzas.jpg"},
	{id: 18, nombre: "Tostaditas", tipo: "Salados", unidad: "Precio x kg", precio: 700, img: "Imagenes/Salados/Tostaditas.jpg"},
	{id: 19, nombre: "Selva Negra", tipo: "Tortas", unidad: "Precio x kg", precio: 1090, img: "Imagenes/Tortas/Selva Negra.jpg"},
	{id: 20, nombre: "Cheesecake", tipo: "Tortas", unidad: "Precio x kg", precio: 1090, img: "Imagenes/Tortas/Cheesecake.jpg"},
	{id: 21, nombre: "Lemon Pie", tipo: "Tortas", unidad: "Precio x kg", precio: 1090, img: "Imagenes/Tortas/Lemon Pie.jpg"},
	{id: 22, nombre: "Brownie", tipo: "Tortas", unidad: "Precio x kg", precio: 1090, img: "Imagenes/Tortas/Brownie.jpg"},
	{id: 23, nombre: "Pirineo", tipo: "Tortas", unidad: "Precio x kg", precio: 1090, img: "Imagenes/Tortas/Pirineo.jpg"},
	{id: 24, nombre: "Marquisse de Chocolate", tipo: "Tortas", unidad: "Precio x kg", precio: 1090, img: "Imagenes/Tortas/Marquisse de Chocolate.jpg"},
	{id: 25, nombre: "Masas Finas", tipo: "Masas", unidad: "Precio x 500g", precio: 600, img: "Imagenes/Masas/Masas Finas.jpg"},
	{id: 26, nombre: "Masas Secas", tipo: "Masas", unidad: "Precio x 500g", precio: 600, img: "Imagenes/Masas/Masas Secas.jpg"},
	{id: 27, nombre: "Baul Grande", tipo: "Bombones", unidad: "Baúl x 45 unidades", precio: 2000, img: "Imagenes/Bombones/Baul Grande.jpg"},
	{id: 28, nombre: "Cajon Grande", tipo: "Bombones", unidad: "Cajon x 20 unidades", precio: 1250, img: "Imagenes/Bombones/Cajon Grande.jpg"},
]